spring.datasource.url=jdbc:mysql://localhost:3306/tano_reservas_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=W}Kimj3w@Xe#L@y:x#C,
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true